name: Reusable Terraform Workflow

on:
  workflow_call:

    inputs:

      environment:
        required: true
        type: string

      tfvars_file:
        required: true
        type: string

      backend_config:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2

jobs:

  terraform:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    defaults:
        working-directory: ./jenkins-server

    steps:

      # =====================================================
      # CHECKOUT CODE
      # =====================================================

      - name: Checkout Repository
        uses: actions/checkout@v4


      # =====================================================
      # CONFIGURE AWS
      # =====================================================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      # =====================================================
      # SETUP TERRAFORM
      # =====================================================

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # =====================================================
      # TERRAFORM INIT
      # =====================================================

      - name: Terraform Init
        run: |
          terraform init \
          -reconfigure \
          -backend-config=${{ inputs.backend_config }}


      # =====================================================
      # TERRAFORM FORMAT CHECK
      # =====================================================

      - name: Terraform Format Check
        run: terraform fmt -check -recursive


      # =====================================================
      # TERRAFORM VALIDATE
      # =====================================================

      - name: Terraform Validate
        run: terraform validate


      # =====================================================
      # TERRAFORM PLAN
      # =====================================================

      - name: Terraform Plan
        run: |
          terraform plan \
          -var-file=${{ inputs.tfvars_file }}


      # =====================================================
      # TERRAFORM APPLY
      # =====================================================

      - name: Terraform Apply
        run: |
          terraform destroy \
          -auto-approve \
          -var-file=${{ inputs.tfvars_file }}
